description_file: package://mmtbot_description/urdf/mmtbot.urdf.xacro
bag_file: $ROS_BAGS/mmtbot/11_03_2021.bag
world_link: world
sensors:
  hand_camera:
    link: hand_camera_rgb_optical_frame
    parent_link: ee_link
    child_link: hand_camera_link
    topic_name: /hand_camera/rgb/image_raw
  world_camera:
    link: world_camera_rgb_optical_frame
    parent_link: tripod_right_support
    child_link: world_camera_link
    topic_name: /world_camera/rgb/image_raw
  3dlidar:
    link: 3dlidar
    parent_link: tripod_left_support
    child_link: 3dlidar_base_link
    topic_name: /3dlidar/points
calibration_pattern:
  link: pattern_link
  parent_link: world
  fixed: false
  pattern_type: charuco
  dictionary: DICT_5X5_100
  mesh_file: package://mmtbot_gazebo/models/charuco_800x600/charuco_800x600.dae
  border_size: {x: 0.06, y: 0.045}
  dimension: {x: 0.04, y: 0.03}
  size: 11
  inner_size: 8
anchored_sensor: ""
max_duration_between_msgs: 1000